name: DBT CI/CD Pipeline

on:
  push:
    branches: [ master ]  # Trigger on pushes to the master branch
  pull_request:
    branches: [ master ]  # Trigger on pull requests to the master branch

jobs:
  build-and-test:
    runs-on: windows-latest  # Updated to Windows runner as you're using Windows 11

    steps:
    - uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version

    - name: Install dbt
      run: |
        pip install dbt-snowflake  # Install dbt and dbt-snowflake adapter

    - name: dbt run
      env:
        DBT_ACCOUNT: 'rm31623.central-india.azure'  # Snowflake account from your profile
        DBT_USER: 'arka09'  # Snowflake user from your profile
        DBT_PASSWORD: '${{secrets.SNOWFLAKE_PASSWORD}}'  # Use GitHub secrets for sensitive data
        DBT_ROLE: 'ACCOUNTADMIN'  # Snowflake role from your profile
        DBT_WAREHOUSE: 'COMPUTE_WH'  # Snowflake warehouse from your profile
        DBT_DATABASE: 'SF_DBT_DWH_DB'  # Snowflake database from your profile
        DBT_SCHEMA: 'DEV'  # Snowflake schema from your profile
        DBT_THREADS: 8  # Number of threads from your profile
      run: |
        dbt run --profiles-dir .

    - name: dbt test
      env:
        DBT_ACCOUNT: 'rm31623.central-india.azure'
        DBT_USER: 'arka09'
        DBT_PASSWORD: '${{ secrets.SNOWFLAKE_PASSWORD }}'
        DBT_ROLE: 'ACCOUNTADMIN'
        DBT_WAREHOUSE: 'COMPUTE_WH'
        DBT_DATABASE: 'SF_DBT_DWH_DB'
        DBT_SCHEMA: 'DEV'
        DBT_THREADS: 8
      run: |
        dbt test --profiles-dir .
