name: dbt CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt_run:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install dbt
      run: pip install dbt-snowflake

    - name: Configure dbt profile
      run: |
        mkdir %USERPROFILE%\.dbt\
        echo "SF_DBT_DWH_09:
          outputs:
            dev:
              type: snowflake
              account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
              user: ${{ secrets.SNOWFLAKE_USER }}
              password: ${{ secrets.SNOWFLAKE_PASSWORD }}
              role: ${{ secrets.SNOWFLAKE_ROLE }}
              database: ${{ secrets.SNOWFLAKE_DATABASE }}
              warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
              schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
              threads: 8
              client_session_keep_alive: False
          target: dev" > %USERPROFILE%\.dbt\profiles.yml

    - name: Run dbt models
      run: dbt run --profiles-dir %USERPROFILE%\.dbt\

    - name: Test dbt models
      run: dbt test --profiles-dir %USERPROFILE%\.dbt\
