name: DBT Workflow

on: [push]

jobs:
  dbt_run:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt
        run: pip install dbt-snowflake

      - name: Create dbt profile directory
        run: |
          New-Item -Path "$env:USERPROFILE\.dbt" -ItemType Directory -Force
          New-Item -Path "$env:USERPROFILE\.dbt\profiles.yml" -ItemType File -Force

      - name: Configure dbt profile
        run: |
          $profile = @"
          SF_DBT_DWH_09:
            outputs:
              dev:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
                threads: 8
                client_session_keep_alive: False
            target: dev
          "@
          $profile | Out-File -FilePath "$env:USERPROFILE\.dbt\profiles.yml"

      - name: Run dbt models
        run: dbt run --profiles-dir "$env:USERPROFILE\.dbt"

      - name: Test dbt models
        run: dbt test --profiles-dir "$env:USERPROFILE\.dbt"
